#!/usr/bin/env python3
import asyncio
from client_code.client_main import main

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\nExiting...")
